ARG ROS2_DISTRO="not-set"
FROM ros:${ROS2_DISTRO}
ARG ROS2_DISTRO

# COPY ./my_msgs /ws/src/my_msgs

# WORKDIR /ws

# RUN bash -c "source /opt/ros/$ROS_DIST/setup.bash && colcon build" 

# do "source /ws/install/setup.bash" before run intdash ROS2Bridge 
