upstream:
- id: up-ros-data

downstream:
- id: down-ros-data
  dest_ids:
  - dc-down-ros-data
  filters:
  - src_edge_uuid: <Controller Edge UUID>
    data_filters:
    - type: '#'
      name: '#'

device_connectors_upstream:
- id: dc-up-ros-data
  data_name_prefix: v1/10/
  dest_ids:
  - up-ros-data
  enabled: true
  format: iscp-v2-compat
  ipc:
    type: fifo
    path: /var/run/intdash/up-ros-data.fifo

device_connectors_downstream:
- id: dc-down-ros-data
  data_name_prefix: ""
  enabled: true
  format: iscp-v2-compat
  ipc:
    type: fifo
    path: /var/run/intdash/down-ros-data.fifo
    
streamer:
  auto_start: true
  log_file: /tmp/intdash-agent-streamer.log
